# Converted from Snowflake to StarRocks
# Generated by Snowflake-to-StarRocks Conversion System
# Please review and test before production use

"""Example Snowflake script for testing conversion."""

Here's the StarRocks connection code in the requested format:

import pymysql

try:
    conn = pymysql.connect(
        user='myuser',
        password='mypassword',
        database='mydb',
        host='localhost',
        port=9030
    )
except pymysql.Error as e:
    print(f"Error connecting to StarRocks: {e}")
    conn = None

# Example query with various Snowflake-specific features
query = """
SELECT user_id,
       CAST(name AS VARCHAR) AS user_name,
       CAST(email AS VARCHAR) AS user_email,
       CAST(metadata AS JSON) AS user_metadata,
       CAST(created_at AS DATETIME) AS created_timestamp,
       PARSE_JSON(preferences):CAST(theme AS VARCHAR) AS theme,
       IF(status = 'active', 1, 0) AS is_active,
       DATE_ADD(DAY, 7, created_at) AS week_later,
       COUNT(*) OVER (PARTITION BY status) AS status_count
FROM users
WHERE created_at >= STR_TO_DATE('2024-01-01')
  AND status IN ('active',
                 'pending')
ORDER BY created_at DESC
LIMIT 100
"""

# Execute query
cursor = conn.cursor()
try:
    cursor.execute(query)
    results = cursor.fetchall()
    
    for row in results:
        print(row)
        
finally:
    cursor.close()
    conn.close()
